version: "3"

services:
  pdf-template:
    container_name: "pdf-template"
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3100:3000"
  gotenberg:
    container_name: "gotenberg"
    image: gotenberg/gotenberg:7
    ports:
      - "3200:3000"